packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  ethers: "^6.11.1"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  bufferutil: true
  es5-ext: true
  esbuild: true
  keccak: true
  prisma: true
  protobufjs: true
  secp256k1: true
  bcrypt: true
  msgpackr-extract: true
  utf-8-validate: true
