services:
  - type: web
    name: cleancity-pwa
    runtime: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npx pnpm install --no-frozen-lockfile && npx pnpm build:pwa
    startCommand: npx pnpm --filter pwa start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
